services:
  ansible-mcp:
    image: ansible-mcp
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: ansible-mcp
    working_dir: /app/ansible-mcp
    ports:
      - "9000:9000"

    environment:
      REQUIRE_AUTH: "1"        # 開発でバイパスするなら 0、本番は 1
      MCP_TOKEN: "secret123"   # ← 固定で良ければこのまま。毎回注入するなら消してOK
      MCP_SERVER_VERSION: v1
      MCP_LOG_DIR: /app/ansible-mcp/logs
      ANSIBLE_BIN: /usr/local/bin/ansible-playbook
      ANSIBLE_INVENTORY: /app/ansible-mcp/inventory.ini
    volumes:
      - ./:/app/ansible-mcp:rw
#      - ./knowledge:/app/knowledge:rw
#      - ./playbooks:/app/playbooks:rw
#      - ./inventory.ini:/app/inventory.ini:ro
#      - ./logs:/app/logs:rw
      # Docker connection plugin needs host docker daemon socket. On macOS/Linux the canonical path is /var/run/docker.sock
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command:
      [
        "uvicorn","mcp_http:app",
        "--host","0.0.0.0",
        "--port","9000",
        "--proxy-headers",
        "--forwarded-allow-ips","*",
        "--access-log",
        "--log-level","info"
      ]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    tmpfs:
      - /var/log
      - /tmp
      - /var/tmp
    networks: [mgmtnet]

networks:
  mgmtnet:
    external: true
