services:
  ansible-mcp:
    image: ansible-mcp
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: ansible-mcp
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    environment:
      REQUIRE_AUTH: "1"   # 開発中はバイパスでOK（本番は必ず戻す）
      MCP_TOKEN: "secret123"     
      MCP_SERVER_VERSION: v1
      MCP_LOG_DIR: /app/logs
      ANSIBLE_BIN: /usr/local/bin/ansible-playbook 
      ANSIBLE_INVENTORY: /app/inventory.ini
    volumes:
      - /Users/naoki/devNet/mcp-ansible-wrapper/knowledge:/app/knowledge:rw
      - /Users/naoki/devNet/mcp-ansible-wrapper/playbooks:/app/playbooks:rw
      - /Users/naoki/devNet/mcp-ansible-wrapper/inventory.ini:/app/inventory.ini:ro
      - /Users/naoki/devNet/mcp-ansible-wrapper/logs:/app/logs:rw
      - /Users/naoki/.orbstack/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: [
      "uvicorn","mcp_http:app",
      "--host","0.0.0.0",
      "--port","9000",
      "--proxy-headers",
      "--forwarded-allow-ips","*",
      "--access-log",
      "--log-level","info"
    ]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    tmpfs:
      - /var/log
      - /tmp
      - /var/tmp
    networks: [mgmtnet]
networks:
  mgmtnet:
    external: true
