services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: mcp
    ports:
      - "9000:9000"
    environment:
      AUTH_DEBUG: "1"
      REQUIRE_AUTH: "1"   # 開発中はバイパスでOK（本番は必ず戻す）
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      MCP_TOKEN: "secret123"     
      MCP_API_TOKEN: ${MCP_TOKEN:-secret123}
      MCP_ALLOW: ${MCP_ALLOW:-playbooks/*.yml}
      MCP_WORKDIR: ${MCP_WORKDIR:-/app}
      LOG_DIR: /app/logs
      LOG_JSONL: "1"
      OPENAI_MODEL_PLAN: gpt-4o-mini
      OPENAI_MODEL_SUM: gpt-4o-mini
      ANSIBLE_RUN: exec
      ANSIBLE_BIN: /usr/local/bin/ansible-playbook 
    volumes:
      - ./knowledge:/app/knowledge:ro
      - ./playbooks:/app/playbooks:ro
      - ./playbooks:/app/playbooks:rw
      - ./inventory.ini:/app/inventory.ini:ro   # ← 正解
      - ./logs:/app/logs
      - ./mcp_http.py:/app/mcp_http.py:ro   # ★これを追加
      - ./knowledge:/app/knowledge:ro
    restart: unless-stopped
    command: [
      "uvicorn","mcp_http:app",
      "--host","0.0.0.0",
      "--port","9000",
      "--proxy-headers",
      "--forwarded-allow-ips","*",
      "--access-log",
      "--log-level","info"
    ]
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9000/health"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 10s   # ← これを追加
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    tmpfs:
      - /var/log
      - /tmp
      - /var/tmp
    networks: [mgmtnet]
networks:
  mgmtnet:
    external: true
