---
- name: Detect FRR (vtysh)
  command: which vtysh
  register: which_vtysh
  changed_when: false
  failed_when: false

- name: Decide platform
  set_fact:
    platform: >-
      {{
        (ansible_network_os | default('')) |
        ternary(ansible_network_os,
          (which_vtysh.rc == 0) | ternary('frr','ios'))
      }}

- include_tasks: frr.yml
  when: platform in ['frr']

- include_tasks: ios.yml
  when: platform in ['ios']

- fail:
    msg: "Unsupported platform for bgp_deep: {{ platform | default('unknown') }}"
  when: platform is not defined or platform not in ['frr','ios']
