---
- name: FRR connectivity and status check
  hosts: "{{ host | default('routers') }}"
  gather_facts: false
  tasks:
    - name: Check vtysh presence
      ansible.builtin.shell: command -v vtysh || true
      register: vtysh_path
      changed_when: false

    - name: Resolve host key (short name)
      ansible.builtin.set_fact:
        host_key: "{{ inventory_hostname.split('.')[0] }}"

    - name: Show FRR version
      ansible.builtin.command: vtysh -c 'show version'
      register: frr_version
      changed_when: false
      when: vtysh_path.stdout != ""

    - name: Show BGP summary
      ansible.builtin.command: vtysh -c 'show ip bgp summary'
      register: bgp_summary
      failed_when: false
      changed_when: false
      when: vtysh_path.stdout != ""

    - name: Print outputs (when vtysh exists)
      ansible.builtin.debug:
        msg:
          - "Host: {{ host_key }}"
          - "FRR Version:\n{{ frr_version.stdout | default('') }}"
          - "BGP Summary:\n{{ bgp_summary.stdout | default('N/A') }}"
      when: vtysh_path.stdout != ""

    - name: Note when vtysh is missing
      ansible.builtin.debug:
        msg: |
          Host: {{ host_key }}
          FRR/OSPF/BGP の確認をスキップしました（vtysh が見つかりません）。
      when: vtysh_path.stdout == ""

