---
- name: Router count
  hosts: routers
  gather_facts: false

  tasks:
    - name: Show router count (run once)
      run_once: true
      debug:
        msg: "routers = {{ groups['routers'] | length }}"
