---
- name: Router ARP table via CLI
  hosts: "{{ host | default('routers') }}"
  gather_facts: no
  vars:
    _mgmt_address: "{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}"
    _is_router: >-
      {{
        ('routers' in group_names)
        or (hostvars[inventory_hostname].device_role | default('')).lower() in ['router','edge-router','core-router']
        or (inventory_hostname is match('^(r|R)[0-9].*'))
      }}
    _arp_table: []

  tasks:
    - name: Gather ARP table
      ansible.builtin.command:
        cmd: ip -json neigh show
      register: _ip_neigh
      changed_when: false
      failed_when: false
      when: _is_router

    - name: Parse ARP table
      ansible.builtin.set_fact:
        _arp_table: "{{ (_ip_neigh.stdout | default('[]', true)) | from_json | default([]) }}"
      when:
        - _is_router
        - (_ip_neigh.stdout | default('')) | length > 0

    - name: Emit ARP payload
      ansible.builtin.debug:
        msg: >
          {{
            {
              "host": inventory_hostname,
              "address": _mgmt_address,
              "arp_table": _arp_table | default([])
            } | to_json
          }}
      when: _is_router
