---
- name: ospf ops for {{ host | default('all') }}
  hosts: "{{ host | default('all') }}"
  gather_facts: no
  tasks:
    - name: Check vtysh presence
      ansible.builtin.shell: command -v vtysh || true
      register: vtysh_path
      changed_when: false

    - name: Strict mode fail when vtysh missing
      ansible.builtin.fail:
        msg: |
          Machine summary (JSON):
          {"code":"no_vtysh_strict","message":"vtysh not found (strict mode)","hint":"Target FRR device may not be reachable from current Ansible connection."}
      when: (vtysh_path.stdout == "") and ((strict_frr | default(true)) | bool)

    - name: show ospf neighbor (when vtysh exists)
      ansible.builtin.shell: |
        vtysh -c 'show ip ospf neighbor' || true
      register: out
      when: vtysh_path.stdout != ""

    - name: print ospf neighbor
      ansible.builtin.debug:
        msg: "{{ out.stdout | default('') }}"
      when: vtysh_path.stdout != ""
