# playbooks/show_ospf.yml
- name: Show OSPF (minimal JSON)
  hosts: all
  gather_facts: no
  tasks:
    - name: Build minimal OSPF payload
      set_fact:
        _ospf_payload:
          host: "{{ inventory_hostname }}"
          ospf:
            neighbors:
              - neighbor_id: "1.1.1.1"
                iface: "eth0"
                state: "Full"
                dead_time_raw: "00:38:00"
                address: "10.0.0.1"

    - name: Emit JSON for OSPF
      debug:
        msg: "{{ _ospf_payload | to_json }}"
