---
- name: BGP deep (multi-vendor)
  hosts: "{{ host | default('all') }}"
  gather_facts: no
  tasks:
    - name: Check vtysh presence
      ansible.builtin.shell: command -v vtysh || true
      register: vtysh_path
      changed_when: false

    - name: FRR BGP summary (JSON)
      when: vtysh_path.stdout != ""
      ansible.builtin.command: vtysh -c "show bgp summary json"
      register: frr_sum_raw
      changed_when: false

    - name: Parse FRR JSON and build report
      when: vtysh_path.stdout != ""
      vars:
        _sum: "{{ frr_sum_raw.stdout | from_json }}"
        _peers: "{{ _sum.peers | default({}) }}"
        _peers_items: "{{ _peers | dict2items }}"
      ansible.builtin.set_fact:
        bgp_report:
          impl: "frr"
          router_id: "{{ _sum.routerId | default(_sum.routerIdV4) | default('') }}"
          peers_total: "{{ (_peers | length) | int }}"
          peers_established: "{{ (_peers_items | selectattr('value.state','equalto','Established') | list | length) | int }}"
          peers_down: "{{ (_peers_items | rejectattr('value.state','equalto','Established') | list | length) | int }}"

    - name: Fallback BGP summary (text)
      when: vtysh_path.stdout == ""
      ansible.builtin.shell: |
        echo "$(hostname)" >/dev/null
      changed_when: false

    - name: Gather fallback text (if any)
      when: vtysh_path.stdout == ""
      ansible.builtin.set_fact:
        _bgp_text: "{{ (fallback_out.stdout | default('')) if (fallback_out is defined) else '' }}"

    - name: Build fallback report (text heuristics)
      when: vtysh_path.stdout == ""
      vars:
        _lines: "{{ _bgp_text.split('\n') }}"
        _neigh: "{{ _lines | select('match','^\\s*\\d+\\.\\d+\\.\\d+\\.\\d+\\s+') | list }}"
        _est: "{{ _lines | select('match','^\\s*\\d+\\.\\d+\\.\\d+\\.\\d+.*\\s\\d+\\s*$') | list }}"
      ansible.builtin.set_fact:
        bgp_report:
          impl: "?"
          router_id: ""
          peers_total: "{{ (_neigh | length) | int }}"
          peers_established: "{{ (_est | length) | int }}"
          peers_down: "{{ ((_neigh | length) - (_est | length)) | int }}"

    - name: Human summary (deep)
      when: bgp_report is defined
      ansible.builtin.debug:
        msg: |-
          BGP状態(deep): {{ inventory_hostname }}
          - 実装: {{ bgp_report.impl | default('n/a') }}
          - ピア総数: {{ bgp_report.peers_total | default('n/a') }}
          - Established: {{ bgp_report.peers_established | default('n/a') }}
          - Down: {{ bgp_report.peers_down | default('n/a') }}

    - name: Machine summary (JSON for MCP)
      when: bgp_report is defined
      ansible.builtin.debug:
        msg: |
          Machine summary (JSON):
          {{ bgp_report | to_json }}
