---
- hosts: "{{ host | default('all') }}"
  gather_facts: no
  vars:
    ospf_report_depth: "summary"
  tasks:
    - name: Gather OSPF summary
      ansible.builtin.import_role:
        name: ospf_report
      vars:
        ospf_report_depth: "summary"

    - name: Emit OSPF summary
      ansible.builtin.debug:
        msg: "{{ ospf_report }}"


x_meta:
  intent: show_ospf
  role: router
  scope: single
  target_group: routers
  tags: [ospf, neighbor, adjacency, summary, routing]
