---
- hosts: "{{ host | default('all') }}"
  gather_facts: no
  vars:
    want_afis: "{{ afi | default(['ipv4 unicast', 'ipv6 unicast']) }}"
  tasks:
    - name: Gather BGP deep report
      ansible.builtin.import_role:
        name: bgp_deep

    - name: Emit BGP deep report (JSON)
      ansible.builtin.debug:
        msg: "{{ bgp_report }}"
